services:
    # Frontend service
    - name: frontend-domenico-angri
      type: web
      env: node
      dir: apps/frontend # Relative path to frontend in monorepo
      buildCommand: npm install && npm run build
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: BACKEND_URL
            sync: false # Tells Render that this variable will be set manually
      routes:
          # Redirect all requests to /admin to Strapi backend
          - type: rewrite
            source: /admin
            destination: ${BACKEND_URL}/admin

          # Handles all nested paths under /admin
          - type: rewrite
            source: /admin/**
            destination: ${BACKEND_URL}/admin/**

          # Handles Strapi API requests
          - type: rewrite
            source: /api/**
            destination: ${BACKEND_URL}/api/**

          # Handles uploaded files (uploads, media)
          - type: rewrite
            source: /uploads/**
            destination: ${BACKEND_URL}/uploads/**

          # SPA routing - redirects all other routes to index.html for client-side routing
          - type: rewrite
            source: /*
            destination: /index.html

      # Custom domain configuration
      domains:
          - name: www.domenicoangri.it

    # Backend Strapi service
    - name: backend-strapi-domenico
      type: web
      env: node
      dir: apps/backend # Relative path to backend in monorepo
      buildCommand: npm install && npm run build
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          # Other environment variables required for Strapi
