// export const italianGreetings = [
//     { text: "Ciao", language: "Italiano" },
//     { text: "Hello", language: "Inglese" },
//     { text: "Hola", language: "Spagnolo" },
//     { text: "Bonjour", language: "Francese" },
//     { text: "Hallo", language: "Tedesco" },
//     { text: "你好 (Nǐ hǎo)", language: "Cinese" },
//     { text: "こんにちは (Konnichiwa)", language: "Giapponese" },
//     { text: "안녕하세요 (Annyeonghaseyo)", language: "Coreano" },
//     { text: "Hej", language: "Svedese" },
//     { text: "Szia", language: "Ungherese" },
//     { text: "Здравствуйте (Zdravstvuyte)", language: "Russo" },
//     { text: "नमस्ते (Namaste)", language: "Hindi" },
//     { text: "مرحبا (Marhaba)", language: "Arabo" },
//     { text: "Olá", language: "Portoghese" },
//     { text: "Γεια σας (Geia sas)", language: "Greco" },
//     { text: "สวัสดี (Sawatdee)", language: "Tailandese" },
//     { text: "Salam", language: "Persiano" },
//     { text: "Xin chào", language: "Vietnamita" },
//     { text: "Sawubona", language: "Zulu" },
//     { text: "Jambo", language: "Swahili" },
// ];

export const italianGreetings = [
    { text: "Ciao", language: "Italiano" },
    { text: "Hello", language: "Inglese" },
    { text: "Hola", language: "Spagnolo" },
    { text: "Bonjour", language: "Francese" },
    { text: "Hallo", language: "Tedesco" },
    { text: "你好", language: "Cinese" },
    { text: "こんにちは", language: "Giapponese" },
    { text: "안녕하세요", language: "Coreano" },
    { text: "Hej", language: "Svedese" },
    { text: "สวัสดี", language: "Tailandese" },
    { text: "Szia", language: "Ungherese" },
    { text: "Здравствуйте", language: "Russo" },
    { text: "नमस्ते", language: "Hindi" },
    { text: "مرحبا ", language: "Arabo" },
    { text: "Olá", language: "Portoghese" },
    { text: "Γεια σας", language: "Greco" },
    { text: "Salam", language: "Persiano" },
    { text: "Xin chào", language: "Vietnamita" },
    { text: "Sawubona", language: "Zulu" },
    { text: "Jambo", language: "Swahili" },
];

export const englishGreetings = [
    { text: "Ciao", language: "Italian" },
    { text: "Hello", language: "English" },
    { text: "Hola", language: "Spanish" },
    { text: "Bonjour", language: "French" },
    { text: "Hallo", language: "German" },
    { text: "你好 (Nǐ hǎo)", language: "Chinese" },
    { text: "こんにちは (Konnichiwa)", language: "Japanese" },
    { text: "안녕하세요 (Annyeonghaseyo)", language: "Korean" },
    { text: "Hej", language: "Swedish" },
    { text: "Szia", language: "Hungarian" },
    { text: "Здравствуйте (Zdravstvuyte)", language: "Russian" },
    { text: "नमस्ते (Namaste)", language: "Hindi" },
    { text: "مرحبا (Marhaba)", language: "Arabic" },
    { text: "Olá", language: "Portuguese" },
    { text: "Γεια σας (Geia sas)", language: "Greek" },
    { text: "สวัสดี (Sawatdee)", language: "Thai" },
    { text: "Salam", language: "Persian" },
    { text: "Xin chào", language: "Vietnamese" },
    { text: "Sawubona", language: "Zulu" },
    { text: "Jambo", language: "Swahili" },
];
